version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development
      - PORT=3003
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev  # Using nodemon for development
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4173:4173"  # Vite's default dev server port
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host  # Vite dev server with host flag
    depends_on:
      - server
    restart: unless-stopped

networks:
  default:
    name: travel-planner-network