services:
  server:
    image: travel-planner-server:latest
    ports:
      - "127.0.0.1:3003:3003"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - PORT=3003
    restart: unless-stopped

client:
    image: travel-planner-client:latest
    ports:
      - "127.0.0.1:4173:4173"
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://plan-my-trip.logsfixer.com
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    build:
      context: ./client
      args:
        - VITE_API_URL=https://plan-my-trip.logsfixer.com
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    depends_on:
      - server
    restart: unless-stopped