version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3003:3003"  # This port matches your Nginx proxy_pass
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - PORT=3003
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3002:3002"  # This port matches your Nginx proxy_pass
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - server
    restart: unless-stopped